{% set name = "readfcs" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/readfcs-{{ version }}.tar.gz
  sha256: dc10e1d7b31cd6b008f0fcdb8bae7d979cd71ae948d2927e5f201afaa72d6e93

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - lamin_utils
    - fcsparser
    - anndata

test:
  imports:
    - readfcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/laminlabs/readfcs
  summary: Parse fcs files into AnnData.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
