{% set name = "readfcs" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/readfcs-{{ version }}.tar.gz
  sha256: feac46ea84d7c53781950f3f74555aa944405d363cd5057774699951c1048df2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.7
    - lamin_utils
    - fcsparser
    - anndata

test:
  imports:
    - readfcs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/laminlabs/readfcs
  summary: Parse fcs files into AnnData.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - berombau
